const sources = [
  {
    name: "Ak-Suu Hot Springs",
    nameRu: "Горячие источники Ак-Суу",
    region: "Ak-Suu",
    regionRu: "Ак-Суу",
    coords: [42.473, 78.546],
    temp: "70°C",
    depth: "150m",
    activity: "Высокая",
    activityEn: "High",
    saving: 1200,
    potential: "Коммерческое использование",
    potentialEn: "Commercial use",
  },
  {
    name: "Jeti-Oguz Springs",
    nameRu: "Источники Джети-Огуз",
    region: "Jeti-Oguz",
    regionRu: "Джети-Огуз",
    coords: [42.345, 78.289],
    temp: "55°C",
    depth: "200m",
    activity: "Средняя",
    activityEn: "Medium",
    saving: 800,
    potential: "Жилое отопление",
    potentialEn: "Residential heating",
  },
  {
    name: "Barbulak Springs",
    nameRu: "Источники Барбулак",
    region: "Barbulak",
    regionRu: "Барбулак",
    coords: [42.123, 77.891],
    temp: "45°C",
    depth: "300m",
    activity: "Низкая",
    activityEn: "Low",
    saving: 400,
    potential: "Экспериментальное использование",
    potentialEn: "Experimental use",
  },
  {
    name: "Jyrgalang Springs",
    nameRu: "Источники Джыргалан",
    region: "Jyrgalang",
    regionRu: "Джыргалан",
    coords: [42.620, 78.420],
    temp: "65°C",
    depth: "170m",
    activity: "Высокая",
    activityEn: "High",
    saving: 1000,
    potential: "Коммерческое использование",
    potentialEn: "Commercial use",
  },
  {
    name: "Cholpon-Ata Hot Springs",
    nameRu: "Горячие источники Чолпон-Ата",
    region: "Cholpon-Ata",
    regionRu: "Чолпон-Ата",
    coords: [42.650, 77.080],
    temp: "50°C",
    depth: "190m",
    activity: "Средняя",
    activityEn: "Medium",
    saving: 600,
    potential: "Жилое отопление",
    potentialEn: "Residential heating",
  },
  {
    name: "Kosh-Kol Springs",
    nameRu: "Источники Кош-Кол",
    region: "Kosh-Kol",
    regionRu: "Кош-Кол",
    coords: [42.570, 77.050],
    temp: "48°C",
    depth: "210m",
    activity: "Низкая",
    activityEn: "Low",
    saving: 350,
    potential: "Экспериментальное использование",
    potentialEn: "Experimental use",
  },
  {
    name: "Alamedin Hot Springs",
    nameRu: "Горячие источники Аламедин",
    region: "Alamedin",
    regionRu: "Аламедин",
    coords: [42.870, 74.620],
    temp: "40°C",
    depth: "250m",
    activity: "Низкая",
    activityEn: "Low",
    saving: 300,
    potential: "Экспериментальное использование",
    potentialEn: "Experimental use",
  },
];

export default sources;