const sources = [
  {
    name: "Ak-Suu Hot Springs",
    nameRu: "Горячие источники Ак-Суу",
    region: "Ak-Suu",
    regionRu: "Ак-Суу",
    coords: [42.473, 78.546],
    temp: "70°C",
    depth: "150m",
    activity: "Высокая",
    activityEn: "High",
    saving: 1200,
    potential: "Коммерческое использование",
    potentialEn: "Commercial use",
  },
  {
    name: "Jeti-Oguz Springs",
    nameRu: "Источники Джети-Огуз",
    region: "Jeti-Oguz",
    regionRu: "Джети-Огуз",
    coords: [42.345, 78.289],
    temp: "55°C",
    depth: "200m",
    activity: "Средняя",
    activityEn: "Medium",
    saving: 800,
    potential: "Жилое отопление",
    potentialEn: "Residential heating",
  },
  {
    name: "Barbulak Springs",
    nameRu: "Источники Барбулак",
    region: "Barbulak",
    regionRu: "Барбулак",
    coords: [42.123, 77.891],
    temp: "45°C",
    depth: "300m",
    activity: "Низкая",
    activityEn: "Low",
    saving: 400,
    potential: "Экспериментальное использование",
    potentialEn: "Experimental use",
  },
  {
    name: "Jyrgalang Springs",
    nameRu: "Источники Джыргалан",
    region: "Jyrgalang",
    regionRu: "Джыргалан",
    coords: [42.620, 78.420],
    temp: "65°C",
    depth: "170m",
    activity: "Высокая",
    activityEn: "High",
    saving: 1000,
    potential: "Коммерческое использование",
    potentialEn: "Commercial use",
  },
  {
    name: "Cholpon-Ata Hot Springs",
    nameRu: "Горячие источники Чолпон-Ата",
    region: "Cholpon-Ata",
    regionRu: "Чолпон-Ата",
    coords: [42.650, 77.080],
    temp: "50°C",
    depth: "190m",
    activity: "Средняя",
    activityEn: "Medium",
    saving: 600,
    potential: "Жилое отопление",
    potentialEn: "Residential heating",
  },
  {
    name: "Kosh-Kol Springs",
    nameRu: "Источники Кош-Кол",
    region: "Kosh-Kol",
    regionRu: "Кош-Кол",
    coords: [42.570, 77.050],
    temp: "48°C",
    depth: "210m",
    activity: "Низкая",
    activityEn: "Low",
    saving: 350,
    potential: "Экспериментальное использование",
    potentialEn: "Experimental use",
  },
  {
    name: "Alamedin Hot Springs",
    nameRu: "Горячие источники Аламедин",
    region: "Alamedin",
    regionRu: "Аламедин",
    coords: [42.5539, 74.4361],
    temp: "53°C",
    depth: "507m",
    activity: "Средняя",
    activityEn: "Medium",
    saving: 700,
    potential: "Лечебные процедуры и отопление",
    potentialEn: "Therapeutic use and heating",
  },
  {
    name: "Altyn-Arashan Hot Springs",
    nameRu: "Горячие источники Алтын-Арашан",
    region: "Altyn-Arashan",
    regionRu: "Алтын-Арашан",
    coords: [42.5000, 78.4000],
    temp: "50°C",
    depth: "200m",
    activity: "Средняя",
    activityEn: "Medium",
    saving: 600,
    potential: "Лечебные ванны и туризм",
    potentialEn: "Therapeutic baths and tourism",
  },
  {
    name: "Jyrgalan Hot Springs",
    nameRu: "Горячие источники Жыргалан",
    region: "Jyrgalan",
    regionRu: "Жыргалан",
    coords: [42.6000, 77.0000],
    temp: "43°C",
    depth: "250m",
    activity: "Средняя",
    activityEn: "Medium",
    saving: 500,
    potential: "Лечебные процедуры и туризм",
    potentialEn: "Therapeutic use and tourism",
  },
  {
    name: "Ak-Bermet Hot Springs",
    nameRu: "Горячие источники Ак-Бермет",
    region: "Ak-Bermet",
    regionRu: "Ак-Бермет",
    coords: [42.5000, 77.0000],
    temp: "44°C",
    depth: "200m",
    activity: "Средняя",
    activityEn: "Medium",
    saving: 550,
    potential: "Лечебные процедуры и туризм",
    potentialEn: "Therapeutic use and tourism",
  },
  {
    name: "Keremet-Suu Hot Springs",
    nameRu: "Горячие источники Керемет-Суу",
    region: "Keremet-Suu",
    regionRu: "Керемет-Суу",
    coords: [42.5000, 77.0000],
    temp: "48°C",
    depth: "220m",
    activity: "Средняя",
    activityEn: "Medium",
    saving: 650,
    potential: "Лечебные процедуры и горячее водоснабжение",
    potentialEn: "Therapeutic use and hot water supply",
  },
  {
    name: "Djuuku Hot Springs",
    nameRu: "Горячие источники Джууку",
    region: "Djuuku",
    regionRu: "Джууку",
    coords: [42.5000, 77.0000],
    temp: "45°C",
    depth: "230m",
    activity: "Средняя",
    activityEn: "Medium",
    saving: 500,
    potential: "Лечебные процедуры и туризм",
    potentialEn: "Therapeutic use and tourism",
  },
  {
    name: "Inylchek Geothermal Zone",
    nameRu: "Геотермальная зона Иныльчек",
    region: "Inylchek",
    regionRu: "Иныльчек",
    coords: [42.0000, 78.0000],
    temp: "N/A",
    depth: "N/A",
    activity: "Высокая",
    activityEn: "High",
    saving: 1500,
    potential: "Производство электроэнергии (до 1000 МВт)",
    potentialEn: "Electricity generation (up to 1000 MW)",
  }
];

export default sources;