const sources = [
  {
    name: "Ak-Suu Hot Springs",
    nameRu: "Горячие источники Ак-Суу",
    coords: [42.473, 78.546],
    temp: "70°C",
    depth: "150m",
    activity: "Высокая",
    activityEn: "High",
    saving: 1200,
    potential: "Коммерческое использование",
    potentialEn: "Commercial use",
  },
  {
    name: "Jeti-Oguz Springs",
    nameRu: "Источники Джети-Огуз",
    coords: [42.345, 78.289],
    temp: "55°C",
    depth: "200m",
    activity: "Средняя",
    activityEn: "Medium",
    saving: 800,
    potential: "Жилое отопление",
    potentialEn: "Residential heating",
  },
  {
    name: "Barbulak Springs",
    nameRu: "Источники Барбулак",
    coords: [42.123, 77.891],
    temp: "45°C",
    depth: "300m",
    activity: "Низкая",
    activityEn: "Low",
    saving: 400,
    potential: "Экспериментальное использование",
    potentialEn: "Experimental use",
  },
];

export default sources;